dist: bionic
os: linux

notifications:
  email: false

language: c

# blocklist
branches:
  except:
    - gh-pages

env:
  jobs:
    - BOARD='afc-bpm'        -VERSION='3.0' -RTM=''
    - BOARD='afc-bpm'        -VERSION='3.1' -RTM=''
    - BOARD='afc-timing'     -VERSION=''    -RTM='rtm-8sfp'

# Install dependencies
addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

#   Build and check this project
script:
  - ./ci_build.sh

# Generate and deploy documentation
after_success:
  - ./ci_gen_doxy.sh

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: false
    on:
      all_branches: true
