dist: bionic
os: linux

notifications:
  email: false

language: c

# blocklist
branches:
  except:
    - gh-pages

env:
  global:
    - BUILD_DIR=build
    - RELEASE_DIR=release
  jobs:
    - BUILD_TYPE='Release'  BOARD='afc-bpm'        -VERSION='3.0' -RTM=''
    - BUILD_TYPE='Release'  BOARD='afc-bpm'        -VERSION='3.1' -RTM=''
    - BUILD_TYPE='Release'  BOARD='afc-timing'     -VERSION=''    -RTM='rtm-8sfp'

jobs:
  include:
    - env: DEPLOY='all'

# Install dependencies
addons:
  apt:
    packages:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - cmake
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

#   Build and check this project
script:
  - ./ci_build.sh

# Generate and deploy documentation
after_success:
  - ./ci_gen_doxy.sh

before_deploy:
  - . ./ci_deploy.sh

deploy:
  - provider: releases
    token: $GH_RELEASES_TOKEN
    file_glob: true
    file: ${OPENMMC_DEPLOYMENT}
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
      condition: $DEPLOY = "all"

  - provider: pages
    skip_cleanup: true
    local_dir: docs/html
    token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep_history: false
    on:
      all_branches: true
